### ISSUE TITLE
Validate WAV encoding properties

### ISSUE THREAD

**Issue by StephenHodgson** [RageAgainstThePixel/com.utilities.encoder.wav#12]
# Bug Report

[Reports from downstream package](https://github.com/RageAgainstThePixel/com.openai.unity/issues/131) indicate that this library may not be properly encoding wav files as intended.

- [ ] Validate the plugin is generating lossless wav encoding.
- [ ] Add additional unit tests to safeguard against breaking changes in future.

**Comment by WizardHsuWeiChe** [comment]
I found if you passed PCMFormatSize.SixteenBit when using EcdoeToPCM, the output is correct, guess there is something goes wrong in the function EcdoeToPCM
```
public static byte[] EncodeToWav(this AudioClip audioClip, bool trim = false)
        {
            if (audioClip == null)
            {
                throw new ArgumentNullException(nameof(audioClip));
            }

            // prep data
            var frequency = audioClip.frequency;
            var channels = audioClip.channels;
            var pcmData = audioClip.EncodeToPCM(PCMFormatSize.SixteenBit, trim);
```

**Comment by StephenHodgson** [comment]
I use EncodeToPCM in the base Audio package and for the OGG encoder as well, but those seem to be ok.

Thanks for the insight. If you have any other input, please share.
